// Chrome isolado, Auth REST simulado e Firestore emulador. Sem produção.
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http'),assert=require('node:assert/strict'),{spawn}=require('node:child_process');
const root=path.resolve(__dirname,'..'),out=fs.mkdtempSync(path.join(os.tmpdir(),'dl-cards-browser-'));
const UID='WuXcMYo6m3OuQttlk7z22gRjlvn1', PORT=8766, DEBUG=9341;
const {createRequire}=require('node:module'), deps=createRequire(path.join(os.tmpdir(),'dl-textos-tests/package.json'));
const {initializeTestEnvironment}=deps('@firebase/rules-unit-testing'),sdk=deps('firebase/firestore');sdk.setLogLevel('silent');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let chrome,ws,env,n=0;const pending=new Map();
function jwt(uid){const enc=x=>Buffer.from(JSON.stringify(x)).toString('base64url');const now=Math.floor(Date.now()/1000);return enc({alg:'none',typ:'JWT'})+'.'+enc({iss:'https://securetoken.google.com/demo-dl-textos',aud:'demo-dl-textos',auth_time:now,user_id:uid,sub:uid,iat:now,exp:now+3600,firebase:{sign_in_provider:'custom'}})+'.';}
const server=http.createServer(async(req,res)=>{
 if(req.method==='OPTIONS'){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','*');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.writeHead(204);res.end();return;}
 res.setHeader('Access-Control-Allow-Origin','*');
 if(req.method==='POST')console.log('Auth local: '+req.url.split('?')[0]);
 if(req.method==='POST'&&req.url.includes('accounts:signInWithCustomToken')){let body='';for await(const c of req)body+=c;const uid=JSON.parse(body).token;res.setHeader('Content-Type','application/json');res.end(JSON.stringify({idToken:jwt(uid),refreshToken:'fixture-refresh-'+uid,expiresIn:'3600',isNewUser:false}));return;}
 if(req.method==='POST'&&req.url.includes('accounts:lookup')){let body='';for await(const c of req)body+=c;const token=JSON.parse(body).idToken;const uid=JSON.parse(Buffer.from(token.split('.')[1],'base64url').toString()).sub;res.setHeader('Content-Type','application/json');res.end(JSON.stringify({users:[{localId:uid,email:uid+'@example.test',emailVerified:true,providerUserInfo:[],createdAt:String(Date.now()),lastLoginAt:String(Date.now())}]}));return;}
 const u=new URL(req.url,'http://local');let relative=decodeURIComponent(u.pathname).replace(/^\//,'');if(relative.endsWith('/'))relative+='index.html';if(!relative)relative='index.html';const f=path.resolve(root,'webapp',relative);if(!f.startsWith(path.resolve(root,'webapp')+path.sep)){res.writeHead(403);res.end();return;}
 try{let b=fs.readFileSync(f);if(relative==='cards/dados.js'){
   b=b.toString().replace('onAuthStateChanged }','onAuthStateChanged, connectAuthEmulator, signInWithCustomToken }').replace('deleteDoc }','deleteDoc, connectFirestoreEmulator }').replace("projectId:'ricardo-d6119'","projectId:'demo-dl-textos'");
   b=b.replace('const auth=getAuth(app), db=getFirestore(app);',`const auth=getAuth(app), db=getFirestore(app); connectAuthEmulator(auth,'http://127.0.0.1:${PORT}',{disableWarnings:true});connectFirestoreEmulator(db,'127.0.0.1',8188);window.DL_TEST={signIn:u=>signInWithCustomToken(auth,u).then(()=>true)};`);
   b=b.replace('export const entrar=()=>signInWithPopup(auth,new GoogleAuthProvider());',`export const entrar=()=>signInWithCustomToken(auth,'${UID}');`);
 }
 const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.webmanifest':'application/manifest+json','.png':'image/png'};res.setHeader('Content-Type',mime[path.extname(f)]||'application/octet-stream');res.setHeader('Cache-Control','no-store');res.end(b);
 }catch{res.writeHead(404);res.end();}
});
const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++n;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
async function evaluate(expression){const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;}
async function until(expression){for(let i=0;i<100;i++){if(await evaluate(expression))return;await sleep(100);}throw Error('Tempo esgotado: '+expression+'\n'+await evaluate('document.body.innerText'));}
async function start(){chrome=spawn('C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless=new','--disable-gpu','--no-first-run','--remote-debugging-port='+DEBUG,'--user-data-dir='+path.join(out,'profile'),'about:blank'],{windowsHide:true,stdio:'ignore'});let tabs;for(let i=0;i<60;i++){try{tabs=await(await fetch('http://127.0.0.1:'+DEBUG+'/json')).json();if(tabs.some(t=>t.type==='page'))break;}catch{}await sleep(200);}ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));ws.addEventListener('message',e=>{const m=JSON.parse(e.data),p=pending.get(m.id);if(p){pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}});await send('Page.enable');await send('Network.enable');await send('Network.setBlockedURLs',{urls:['https://identitytoolkit.googleapis.com/*','https://securetoken.googleapis.com/*','https://firestore.googleapis.com/*','https://www.gstatic.com/*','https://ricardo-d6119*/*']});}
async function stop(){try{await send('Browser.close');}catch{}ws.close();await sleep(600);}
const click=async id=>{await until(`!document.getElementById(${JSON.stringify(id)}).disabled`);return evaluate(`document.getElementById(${JSON.stringify(id)}).click()`);};
const value=(id,v)=>evaluate(`(()=>{const e=document.getElementById(${JSON.stringify(id)});e.value=${JSON.stringify(v)};e.dispatchEvent(new Event('input',{bubbles:true}));})()`);
async function main(){await new Promise(r=>server.listen(PORT,'127.0.0.1',r));env=await initializeTestEnvironment({projectId:'demo-dl-textos',firestore:{host:'127.0.0.1',port:8188,rules:fs.readFileSync(path.join(root,'firestore.rules'),'utf8')}});await env.clearFirestore();
 const c=JSON.parse(fs.readFileSync(path.join(root,'webapp/cards/texto-01.json'),'utf8'));
 const original=[...new Set(Object.values(c.secoes).flat().map(i=>i.origem).filter(Boolean))];original.splice(1,0,'Über dem Wasser liegt leichter Nebel.');original.push('Am Ufer sehe ich einen kleinen Vogel.','Dort mache ich mir einen Kaffee.');
 await env.withSecurityRulesDisabled(async ctx=>{const db=ctx.firestore();await sdk.setDoc(sdk.doc(db,'textos','texto-01'),{titulo:c.titulo,conteudo:original.join('\n'),estado:'recebido',criadoEm:sdk.Timestamp.now()});});
 try{await start();await send('Page.navigate',{url:`http://127.0.0.1:${PORT}/cards/`});await until(`!!window.DL_TEST && !document.getElementById('auth').disabled`);await click('auth');await until(`document.querySelectorAll('#lista button').length===1`);
 await click('importar');await value('texto','texto-01');await value('conteudo','{');await click('validar');await until(`document.getElementById('status').textContent.includes('JSON inválido')`);assert(await evaluate(`document.getElementById('salvar').hidden`));
 await value('conteudo',JSON.stringify(c));await click('validar');await until(`!document.getElementById('salvar').hidden`);assert.equal(await evaluate(`document.querySelectorAll('#preview .item').length`),44);await click('salvar');await until(`document.getElementById('status').textContent.includes('Card salvo')`);assert.equal(await evaluate(`document.querySelectorAll('#card .item').length`),8);
 await click('portugues');assert(await evaluate(`getComputedStyle(document.querySelector('#card .pt')).display==='none'`));await click('modo');assert.equal(await evaluate(`document.querySelectorAll('#card .item').length`),44);
 // HTML permanece texto literal na revisão.
 const rev=structuredClone(c);rev.secoes.sentencas[0].pt='<img src=x onerror="window.EXECUTOU=true">';await click('importar');await value('texto','texto-01');await value('conteudo',JSON.stringify(rev));await click('validar');await until(`!document.getElementById('salvar').hidden`);assert(!await evaluate(`!!document.querySelector('#preview img') || !!window.EXECUTOU`));await click('salvar');await until(`document.getElementById('status').textContent.includes('Card salvo')`);
 for(const [w,h] of [[1440,1000],[390,844],[768,1024]]){await send('Emulation.setDeviceMetricsOverride',{width:w,height:h,deviceScaleFactor:1,mobile:w<800});await click('modo');const report=await evaluate(`({overflow:document.documentElement.scrollWidth>innerWidth,font:getComputedStyle(document.querySelector('#card .de')).fontSize,buttons:[...document.querySelectorAll('#estudo button')].filter(e=>e.getClientRects().length).every(e=>e.getBoundingClientRect().height>=48)})`);assert(!report.overflow,JSON.stringify(report));assert.equal(report.font,'22px');assert(report.buttons);const s=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(out,'cards-'+w+'.png'),Buffer.from(s.data,'base64'));}
 await click('disponibilizar');await until(`document.getElementById('status').textContent.includes('Armazenamento concluído')`);
 await evaluate(`navigator.serviceWorker.register('/sw.js',{scope:'/'}).then(()=>true)`);await sleep(800);await stop();
 // Novo processo, mesmo perfil isolado; todo tráfego HTTP falha.
 await start();await send('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:0,uploadThroughput:0});await send('Page.navigate',{url:`http://127.0.0.1:${PORT}/cards/`});await until(`document.querySelectorAll('#lista button').length===1`);await evaluate(`document.querySelector('#lista button').click()`);await until(`document.querySelectorAll('#card .item').length===8`);assert((await evaluate(`document.getElementById('original').textContent`)).includes('Am frühen Morgen'));await until(`document.getElementById('local').textContent.includes('disponíveis')`);await click('portugues');assert(await evaluate(`getComputedStyle(document.querySelector('#card .pt')).display==='none'`));
 await click('remover');await until(`document.getElementById('status').textContent.includes('Cópia local removida')`);assert.equal(await evaluate(`document.querySelectorAll('#lista button').length`),0);
 await send('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});await click('atualizar');await until(`document.querySelectorAll('#lista button').length===1`);await evaluate(`document.querySelector('#lista button').click()`);await until(`document.querySelectorAll('#card .item').length===8`);await click('disponibilizar');await until(`document.getElementById('status').textContent.includes('Armazenamento concluído')`);
 await evaluate(`window.DL_TEST.signIn('other-account')`);await until(`document.getElementById('card').textContent===''`);assert.equal(await evaluate(`document.getElementById('original').textContent`),'');const locais=await evaluate(`import('./offline.js').then(m=>m.listarLocal('${UID}')).then(x=>x.length)`);assert.equal(locais,0);
 await evaluate(`window.DL_TEST.signIn('${UID}')`);await until(`document.querySelectorAll('#lista button').length===1`);await evaluate(`document.querySelector('#lista button').click()`);await until(`document.querySelectorAll('#card .item').length===8`);await click('disponibilizar');await until(`document.getElementById('status').textContent.includes('Armazenamento concluído')`);
 await evaluate(`window.confirm=()=>true`);await click('excluir');await until(`document.getElementById('status').textContent.includes('Card excluído')`);assert((await evaluate(`document.getElementById('original').textContent`)).includes('Am frühen Morgen'));assert.equal(await evaluate(`import('./offline.js').then(m=>m.listarLocal('${UID}')).then(x=>x.length)`),0);
 await click('importar');await value('texto','texto-01');await value('conteudo',JSON.stringify(c));await click('validar');await until(`!document.getElementById('salvar').hidden`);await click('salvar');await until(`document.getElementById('status').textContent.includes('Card salvo')`);await click('disponibilizar');await until(`document.getElementById('status').textContent.includes('Armazenamento concluído')`);
 await click('auth');await until(`document.getElementById('conta').textContent==='Não conectado'`);assert(await evaluate(`document.getElementById('area').hidden`));assert.equal(await evaluate(`import('./offline.js').then(m=>m.listarLocal('${UID}')).then(x=>x.length)`),0);
 console.log('PASS: importação inválida/válida, revisão, HTML inerte, modos, português, 1440/390/768 px, reabertura em novo processo offline com autenticação persistida, remoção local, troca de conta e saída. Evidências: '+out);
 }finally{if(ws)await stop();await env.cleanup();server.close();}
}
main().catch(e=>{console.error(e);server.close();if(chrome)chrome.kill();process.exitCode=1;});
