// Chrome isolado, Auth REST simulado e Firestore emulador. Sem produção.
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http'),assert=require('node:assert/strict'),{spawn}=require('node:child_process');
const root=path.resolve(__dirname,'..'),out=fs.mkdtempSync(path.join(os.tmpdir(),'dl-cards-fluxo-'));
const UID='WuXcMYo6m3OuQttlk7z22gRjlvn1', PORT=8769, DEBUG=9344;
const {createRequire}=require('node:module'), deps=createRequire(path.join(os.tmpdir(),'dl-textos-tests/package.json'));
const {initializeTestEnvironment}=deps('@firebase/rules-unit-testing'),sdk=deps('firebase/firestore');sdk.setLogLevel('silent');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let chrome,ws,env,n=0;const pending=new Map();
function jwt(uid){const enc=x=>Buffer.from(JSON.stringify(x)).toString('base64url');const now=Math.floor(Date.now()/1000);return enc({alg:'none',typ:'JWT'})+'.'+enc({iss:'https://securetoken.google.com/demo-dl-textos',aud:'demo-dl-textos',auth_time:now,user_id:uid,sub:uid,iat:now,exp:now+3600,firebase:{sign_in_provider:'custom'}})+'.';}
let legacy=true, pacoteFalha=false, aceitarConfirmacao=true;const confirmacoes=[];
const previous=new Map(['index.html','cards.js','cards.css','sw.js'].map(f=>['cards/'+f,require('node:child_process').execFileSync('git',['show','96e83b0247becd497332e19509ccc74fae2251ac:webapp/cards/'+f],{cwd:root})]));
const server=http.createServer(async(req,res)=>{
 if(req.method==='OPTIONS'){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','*');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.writeHead(204);res.end();return;}
 res.setHeader('Access-Control-Allow-Origin','*');
 if(req.method==='POST')console.log('Auth local: '+req.url.split('?')[0]);
 if(req.method==='POST'&&req.url.includes('accounts:signInWithCustomToken')){let body='';for await(const c of req)body+=c;const uid=JSON.parse(body).token;res.setHeader('Content-Type','application/json');res.end(JSON.stringify({idToken:jwt(uid),refreshToken:'fixture-refresh-'+uid,expiresIn:'3600',isNewUser:false}));return;}
 if(req.method==='POST'&&req.url.includes('accounts:lookup')){let body='';for await(const c of req)body+=c;const token=JSON.parse(body).idToken;const uid=JSON.parse(Buffer.from(token.split('.')[1],'base64url').toString()).sub;res.setHeader('Content-Type','application/json');res.end(JSON.stringify({users:[{localId:uid,email:uid+'@example.test',emailVerified:true,providerUserInfo:[],createdAt:String(Date.now()),lastLoginAt:String(Date.now())}]}));return;}
 const u=new URL(req.url,'http://local');let relative=decodeURIComponent(u.pathname).replace(/^\//,'');if(relative.endsWith('/'))relative+='index.html';if(!relative)relative='index.html';const f=path.resolve(root,'webapp',relative);if(!f.startsWith(path.resolve(root,'webapp')+path.sep)){res.writeHead(403);res.end();return;}
 if(relative==='cards/texto-01.json' && pacoteFalha){res.writeHead(503);res.end('falha local simulada');return;}
 try{let b=legacy && previous.has(relative)?previous.get(relative):fs.readFileSync(f);if(relative==='cards/dados.js'){
   b=b.toString().replace('onAuthStateChanged }','onAuthStateChanged, connectAuthEmulator, signInWithCustomToken }').replace('deleteDoc }','deleteDoc, connectFirestoreEmulator }').replace("projectId:'ricardo-d6119'","projectId:'demo-dl-textos'");
   b=b.replace('const auth=getAuth(app), db=getFirestore(app);',`const auth=getAuth(app), db=getFirestore(app); connectAuthEmulator(auth,'http://127.0.0.1:${PORT}',{disableWarnings:true});connectFirestoreEmulator(db,'127.0.0.1',8188);window.DL_TEST={signIn:u=>signInWithCustomToken(auth,u).then(()=>true)};`);
   b=b.replace('export const entrar=()=>signInWithPopup(auth,new GoogleAuthProvider());',`export const entrar=()=>signInWithCustomToken(auth,'${UID}');`);
 }
 if(relative==='cards/dados.js'){b=b.toString().replace('export async function salvar(id,u,c){',`export async function salvar(id,u,c){if(window.DL_TEST.falharSalvar)await runTransaction(db,tx=>{tx.set(doc(db,'textos',id,'cards','invalido'),{teste:true});});if(window.DL_TEST.atrasarSalvar)await new Promise(ok=>window.DL_TEST.liberarSalvar=ok);`).replace('export async function carregar(id,u){',`export async function carregar(id,u){if(window.DL_TEST.falharCarregar)throw Error('Leitura local simulada indispon?vel.');if(window.DL_TEST.atrasarCarregar)await new Promise(ok=>window.DL_TEST.liberarCarregar=ok);`);}
 const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.webmanifest':'application/manifest+json','.png':'image/png'};res.setHeader('Content-Type',mime[path.extname(f)]||'application/octet-stream');res.setHeader('Cache-Control','no-store');res.end(b);
 }catch{res.writeHead(404);res.end();}
});
const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++n;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
async function evaluate(expression){const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;}
async function until(expression){for(let i=0;i<100;i++){if(await evaluate(expression))return;await sleep(100);}throw Error('Tempo esgotado: '+expression+'\n'+await evaluate('document.body.innerText'));}
async function start(){chrome=spawn('C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless=new','--disable-gpu','--no-first-run','--remote-debugging-port='+DEBUG,'--user-data-dir='+path.join(out,'profile'),'about:blank'],{windowsHide:true,stdio:'ignore'});let tabs;for(let i=0;i<60;i++){try{tabs=await(await fetch('http://127.0.0.1:'+DEBUG+'/json')).json();if(tabs.some(t=>t.type==='page'))break;}catch{}await sleep(200);}ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));ws.addEventListener('message',e=>{const m=JSON.parse(e.data),p=pending.get(m.id);if(p){pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}});ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.method==='Page.javascriptDialogOpening'){confirmacoes.push(m.params.message);send('Page.handleJavaScriptDialog',{accept:aceitarConfirmacao}).catch(()=>{});}});await send('Page.enable');await send('Network.enable');await send('Network.setBlockedURLs',{urls:['https://identitytoolkit.googleapis.com/*','https://securetoken.googleapis.com/*','https://firestore.googleapis.com/*','https://www.gstatic.com/*','https://ricardo-d6119*/*']});}
async function stop(){try{await send('Browser.close');}catch{}ws.close();await sleep(600);}
const click=async id=>{await until(`!document.getElementById(${JSON.stringify(id)}).disabled`);return evaluate(`document.getElementById(${JSON.stringify(id)}).click()`);};
const value=(id,v)=>evaluate(`(()=>{const e=document.getElementById(${JSON.stringify(id)});e.value=${JSON.stringify(v)};e.dispatchEvent(new Event('input',{bubbles:true}));})()`);
async function escolher(id){await value('texto',id);await evaluate(`document.getElementById('texto').dispatchEvent(new Event('change'))`);await until(`!document.getElementById('validar').disabled`);}
async function texto(id){await until(`!document.querySelector('#lista [data-texto-id="${id}"]')?.disabled`);await evaluate(`document.querySelector('#lista [data-texto-id="${id}"]').click()`);await until(`!document.getElementById('estudo').hidden && !document.getElementById('disponibilizar').disabled`);}
async function secao(id,dest='card'){await evaluate(`document.querySelector('#${dest} [data-secao="${id}"]').click()`);}
async function escape(){await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});}
async function verificar(){await click('validar');await until(`!document.getElementById('salvar').hidden && !document.getElementById('salvar').disabled`);}
async function snapshot(nome){const s=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(out,nome+'.png'),Buffer.from(s.data,'base64'));}
async function main(){
 await new Promise(r=>server.listen(PORT,'127.0.0.1',r));env=await initializeTestEnvironment({projectId:'demo-dl-textos',firestore:{host:'127.0.0.1',port:8188,rules:fs.readFileSync(path.join(root,'firestore.rules'),'utf8')}});await env.clearFirestore();
 const c=JSON.parse(fs.readFileSync(path.join(root,'webapp/cards/texto-01.json'),'utf8'));
 const original=[...new Set(Object.values(c.secoes).flat().map(i=>i.origem).filter(Boolean))].join('\n');
 await env.withSecurityRulesDisabled(async ctx=>{const db=ctx.firestore();for(const [id,titulo] of [['texto-01',c.titulo],['sem-card','Texto sem card']])await sdk.setDoc(sdk.doc(db,'textos',id),{titulo,conteudo:original,estado:'recebido',criadoEm:sdk.Timestamp.now()});await sdk.setDoc(sdk.doc(db,'textos','texto-01','cards',UID),{uid:UID,textoId:'texto-01',versao:1,conteudo:JSON.stringify(c),criadoEm:sdk.Timestamp.now(),atualizadoEm:sdk.Timestamp.now()});});
 async function remoto(id){let r;await env.withSecurityRulesDisabled(async ctx=>{const db=ctx.firestore();const s=await sdk.getDoc(sdk.doc(db,'textos',id,'cards',UID));r=s.exists()?s.data():null;});return r;}
 async function locais(){return evaluate(`import('./offline.js').then(m=>m.listarLocal('${UID}'))`);}
 async function offline(){await click('disponibilizar');await until(`document.getElementById('offline-status').textContent==='✓ Disponível sem internet' && !document.getElementById('disponibilizar').disabled`);}
 try{
  // Cópia já salva e shell anterior; não importar novamente para abrir na nova UI.
  await start();await send('Page.navigate',{url:`http://127.0.0.1:${PORT}/cards/`});await until(`!!window.DL_TEST && !document.getElementById('auth').disabled`);await click('auth');await until(`document.querySelectorAll('#lista button').length===2`);await evaluate(`document.querySelector('#lista button').click()`);await until(`document.querySelectorAll('#card .linha').length===3`);await click('disponibilizar');await until(`document.getElementById('status').textContent.includes('Armazenamento concluído')`);const antiga=JSON.stringify(await locais());await stop();
  legacy=false;await start();await send('Page.navigate',{url:`http://127.0.0.1:${PORT}/cards/`});await until(`document.querySelector('#lista [data-texto-id="texto-01"]') && document.getElementById('importar').textContent==='Adicionar card'`);
  await until(`navigator.serviceWorker.getRegistration('/cards/').then(r=>new Promise(ok=>{if(!r?.active)return ok(false);const c=new MessageChannel();c.port1.onmessage=e=>ok(e.data?.pronto && e.data.versao==='fluxo-4');r.active.postMessage('verificar-shell',[c.port2]);}))`);assert.equal(JSON.stringify(await locais()),antiga);
  assert(await evaluate(`!document.getElementById('editor').open && document.getElementById('estudo').hidden && !document.getElementById('opcoes-entrada').open && document.getElementById('atualizar').closest('details')===document.getElementById('opcoes-entrada')`));assert(!await evaluate(`!!document.getElementById('modo') || !!document.getElementById('modo-preview')`));assert(await evaluate(`document.getElementById('carregar-pacote').closest('dialog')===document.getElementById('editor') && document.querySelector('a[href="modelo.json"]').closest('dialog')===document.getElementById('editor')`));
  await texto('texto-01');assert(await evaluate(`!document.getElementById('consulta').hidden && !document.getElementById('editor').open && !document.getElementById('opcoes-estudo').open && !document.getElementById('ajuda').open`));assert.equal(await evaluate(`document.querySelector('#card [data-secao="duvidas"]').textContent`),'Minhas dúvidas');
  assert.equal(await evaluate(`document.querySelectorAll('#card [data-secao]').length`),7);
  for(const [s,total] of [['duvidas',3],['blocos',5],['sentencas',3],['substantivos',11],['verbos',13],['adjetivos',4],['adverbios',5]]){await secao(s);assert.equal(await evaluate(`document.querySelectorAll('#card .linha').length`),total);assert.equal(await evaluate(`document.querySelectorAll('#card .secao-caixa').length`),1);assert(await evaluate(`[...document.querySelectorAll('#card .contexto')].every(e=>!e.open)`));}
  await secao('duvidas');await click('portugues');assert(await evaluate(`[...document.querySelectorAll('#card .pt')].every(e=>getComputedStyle(e).display==='none')`));assert(!await evaluate(`document.getElementById('card').innerText.includes('Weile = algum tempo')`));await click('portugues');assert((await evaluate(`document.getElementById('card').innerText`)).includes('Weile = algum tempo'));await click('reler');assert.equal(await evaluate(`document.getElementById('original').textContent`),original);await click('reler');assert(await evaluate(`document.getElementById('releitura').hidden`));
  await click('voltar');await texto('sem-card');assert(await evaluate(`!document.getElementById('sem-card').hidden && document.getElementById('consulta').hidden && !document.getElementById('editor').open`));await click('adicionar-para-texto');assert.equal(await evaluate(`document.getElementById('texto').value`),'sem-card');assert(await evaluate(`document.getElementById('editor').open && document.activeElement===document.getElementById('conteudo')`));
  await value('conteudo','Rascunho que não deve desaparecer');aceitarConfirmacao=false;await click('cancelar');assert(await evaluate(`document.getElementById('editor').open && document.getElementById('conteudo').value==='Rascunho que não deve desaparecer'`));aceitarConfirmacao=true;await escape();await until(`!document.getElementById('editor').open`);assert(await evaluate(`document.activeElement===document.getElementById('adicionar-para-texto')`));assert(confirmacoes.slice(-2).every(s=>s.includes('Descartar')));
  await click('voltar');await click('importar');assert(await evaluate(`document.getElementById('editor').open && document.getElementById('texto').value==='' && document.activeElement===document.getElementById('texto')`));
  for(let i=0;i<5;i++){await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});assert(await evaluate(`!!document.activeElement.closest('#editor')`));}
  await escape();await until(`!document.getElementById('editor').open`);assert(await evaluate(`document.activeElement===document.getElementById('importar')`));await click('importar');
  await value('conteudo','{');pacoteFalha=true;await click('carregar-pacote');await until(`document.getElementById('conferencia-status').textContent.includes('Não foi possível carregar')`);assert.equal(await evaluate(`document.getElementById('conteudo').value`),'{');pacoteFalha=false;await click('carregar-pacote');await until(`document.getElementById('conferencia-status').textContent.includes('Texto 01 carregado')`);assert.equal(await evaluate(`document.getElementById('texto').value`),'');assert.deepEqual(JSON.parse(await evaluate(`document.getElementById('conteudo').value`)),c);
  await click('validar');await until(`document.getElementById('texto').getAttribute('aria-invalid')==='true'`);await escolher('sem-card');await value('conteudo','{');await click('validar');await until(`document.getElementById('conferencia-status').textContent.includes('JSON inválido')`);await value('conteudo',JSON.stringify(c));await verificar();assert.equal(await evaluate(`document.querySelectorAll('#preview [data-secao]').length`),7);assert.equal(await remoto('sem-card'),null);
  const digitado=await evaluate(`document.getElementById('conteudo').value`);await evaluate(`window.DL_TEST.falharSalvar=true`);await click('salvar');await until(`!document.getElementById('salvar').disabled && document.getElementById('conferencia-status').textContent!=='Salvando card…'`);assert(await evaluate(`document.getElementById('editor').open && !document.getElementById('salvar').hidden`));assert.equal(await evaluate(`document.getElementById('conteudo').value`),digitado);assert.equal(await remoto('sem-card'),null);assert(!await evaluate(`document.getElementById('salvo-status').textContent.includes('✓ Card salvo')`));
  await evaluate(`window.DL_TEST.falharSalvar=false;window.DL_TEST.atrasarSalvar=true`);await click('salvar');await until(`!!window.DL_TEST.liberarSalvar`);assert(await evaluate(`document.getElementById('editor').open && document.getElementById('conferencia-status').textContent==='Salvando card…'`));assert.equal(await remoto('sem-card'),null);await evaluate(`window.DL_TEST.atrasarSalvar=false;window.DL_TEST.liberarSalvar()`);await until(`!document.getElementById('editor').open && document.getElementById('salvo-status').textContent==='✓ Card salvo'`);assert(await evaluate(`!document.getElementById('consulta').hidden && document.activeElement===document.getElementById('salvo-status')`));const criado=(await remoto('sem-card')).criadoEm.toMillis();assert.equal((await remoto('sem-card')).textoId,'sem-card');
  // Revisão carrega registro atual e protege seu vínculo; cancelamento volta ao botão.
  await evaluate(`document.getElementById('opcoes-estudo').open=true`);await click('revisar');await until(`document.getElementById('editor').open && !document.getElementById('conteudo').disabled`);assert.deepEqual(JSON.parse(await evaluate(`document.getElementById('conteudo').value`)),c);assert(await evaluate(`document.getElementById('texto').disabled && document.getElementById('texto').value==='sem-card' && document.activeElement===document.getElementById('conteudo')`));await escape();await until(`!document.getElementById('editor').open`);assert(await evaluate(`document.activeElement===document.getElementById('revisar')`));
  await click('revisar');await until(`document.getElementById('editor').open && !document.getElementById('conteudo').disabled`);const rev=structuredClone(c);rev.secoes.duvidas[0].pt+=' Revisão do card.';await value('conteudo',JSON.stringify(rev));assert(await evaluate(`document.getElementById('salvar').hidden`));await verificar();await click('salvar');await until(`!document.getElementById('editor').open && document.getElementById('salvo-status').textContent==='✓ Card salvo'`);const revisado=await remoto('sem-card');assert.equal(revisado.criadoEm.toMillis(),criado);assert.deepEqual(JSON.parse(revisado.conteudo),rev);assert.equal(revisado.uid,UID);assert.equal(revisado.textoId,'sem-card');
  // Falha e confirmação de disponibilidade junto à ação, só após armazenamento.
  await evaluate(`window.DL_TEST.falharCarregar=true`);await click('disponibilizar');await until(`document.getElementById('offline-status').textContent.includes('Leitura local simulada')`);assert(!(await locais()).some(l=>l.textoId==='sem-card'));await evaluate(`window.DL_TEST.falharCarregar=false;window.DL_TEST.atrasarCarregar=true`);await click('disponibilizar');await until(`!!window.DL_TEST.liberarCarregar`);assert.equal(await evaluate(`document.getElementById('offline-status').textContent`),'Armazenando card e texto…');assert(!(await locais()).some(l=>l.textoId==='sem-card'));await evaluate(`window.DL_TEST.atrasarCarregar=false;window.DL_TEST.liberarCarregar()`);await until(`document.getElementById('offline-status').textContent==='✓ Disponível sem internet'`);assert((await locais()).some(l=>l.textoId==='sem-card'));assert.equal(await evaluate(`document.getElementById('local').textContent`),'Disponível sem internet');
  await evaluate(`document.getElementById('opcoes-estudo').open=true`);aceitarConfirmacao=false;await click('remover');assert(confirmacoes.at(-1).includes('deste aparelho'));assert((await locais()).some(l=>l.textoId==='sem-card'));aceitarConfirmacao=true;await click('remover');await until(`document.getElementById('opcoes-status').textContent.includes('Cópia deste aparelho removida')`);assert(!(await locais()).some(l=>l.textoId==='sem-card'));assert.deepEqual(JSON.parse((await remoto('sem-card')).conteudo),rev);await offline();
  // Desktop, celular e tablet: mesmos controles/cores/fontes, sem cortes.
  for(const [w,h] of [[1440,1000],[390,844],[768,1024]]){
    await send('Emulation.setDeviceMetricsOverride',{width:w,height:h,deviceScaleFactor:1,mobile:w<800});
    await secao('blocos');await evaluate(`document.getElementById('card').scrollIntoView()`);
    const r=await evaluate(`({overflow:document.documentElement.scrollWidth>innerWidth,font:getComputedStyle(document.querySelector('#card .de')).fontSize,cor:getComputedStyle(document.getElementById('portugues')).backgroundColor})`);assert(!r.overflow,JSON.stringify(r));assert.equal(r.font,'22px');assert.equal(r.cor,'rgb(220, 238, 228)');await snapshot('estudo-'+w);
    await evaluate(`document.getElementById('opcoes-estudo').open=true`);await click('revisar');await until(`document.getElementById('editor').open && !document.getElementById('conteudo').disabled`);await verificar();await secao('blocos','preview');await evaluate(`document.getElementById('preview').scrollIntoView()`);
    const dialogo=await evaluate(`(()=>{const d=document.getElementById('editor'),r=d.getBoundingClientRect();return {inside:r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight,overflow:d.scrollWidth>d.clientWidth,font:getComputedStyle(document.querySelector('#preview .de')).fontSize};})()`);assert(dialogo.inside&&!dialogo.overflow,JSON.stringify(dialogo));assert.equal(dialogo.font,'22px');await snapshot('janela-'+w);await escape();await until(`!document.getElementById('editor').open`);
  }
  await stop();await start();await send('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:0,uploadThroughput:0});await send('Page.navigate',{url:`http://127.0.0.1:${PORT}/cards/`});await until(`document.querySelector('#lista [data-texto-id="sem-card"]')`);await texto('sem-card');assert.equal(await evaluate(`document.querySelectorAll('#card [data-secao]').length`),7);assert(!await evaluate(`document.getElementById('editor').open`));assert((await evaluate(`document.getElementById('card').innerText`)).includes('Revisão do card.'));await secao('verbos');assert.equal(await evaluate(`document.querySelectorAll('#card .linha').length`),13);await click('portugues');assert(await evaluate(`[...document.querySelectorAll('#card .pt')].every(e=>getComputedStyle(e).display==='none')`));await click('reler');assert.equal(await evaluate(`document.getElementById('original').textContent`),original);assert.equal(await evaluate(`document.getElementById('local').textContent`),'Disponível sem internet');
  // Exclusão remota claramente distinta da remoção local, só no emulador.
  await send('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});await click('voltar');await texto('texto-01');await evaluate(`document.getElementById('opcoes-estudo').open=true`);aceitarConfirmacao=false;await click('excluir');assert(confirmacoes.at(-1).includes('apaga o card remoto'));assert(await remoto('texto-01'));aceitarConfirmacao=true;await click('excluir');await until(`!document.getElementById('sem-card').hidden && document.getElementById('consulta').hidden`);assert.equal(await remoto('texto-01'),null);await env.withSecurityRulesDisabled(async ctx=>{assert((await sdk.getDoc(sdk.doc(ctx.firestore(),'textos','texto-01'))).exists());});
  console.log('PASS fluxos alterados: abertura sem reimportação e migração offline; seções completas/contexto/tradução; janela adicionar/revisar; foco/Tab/Escape/descarte; carga/colagem/prévia; falha e sucesso confirmados no emulador; revisão no mesmo UID/ID; confirmações local/remota distintas; desktop 1440, celular 390, tablet 768 sem cortes e fonte 22 px; reabertura offline. Evidências: '+out);
 }finally{if(ws)await stop();await env.cleanup();server.close();}
}
main().catch(e=>{console.error(e);server.close();if(chrome)chrome.kill();process.exitCode=1;});
